import {onBusiness, selfStudy} from './common.js';
import type {SkillItem} from '../types/skillItem.js';

export const nextjsSkillSet = [
  'React',
  'TypeScript',
  'Next.js',
  'Tailwind CSS',
  'Shadcn/ui',
  'Vercel',
];

export const receptionInnovationSkillSet = [
  'Java',
  'Springboot',
  'TypeScript',
  'React',
  'Git',
  'Github',
  'Swagger',
];

export const VOCSkillSet = [
  'Java',
  'Springboot',
  'TypeScript',
  'React',
  'Git',
  'Github',
  'Swagger',
];

export const T3StackSkillSet = [
  'Next.js',
  'TypeScript',
  'Tailwind CSS',
  'tRPC',
  'Prisma',
  'NextAuth.js',
];

// main skills(Language,Libraries)
export const skills: SkillItem[] = [
  {
    name: 'TypeScript',
    years: '1 year 6 months',
    category: 'Language',
    proficiency: onBusiness,
    picture: '/icons/TypeScript.svg',
    pictureColor: '#3178C6',
  },
  {
    name: 'JavaScript(include TypeScript)',
    years: '2 years',
    category: 'Language',
    proficiency: onBusiness,
    picture: '/icons/JavaScript.svg',
    pictureColor: '#F7DF1E',
  },
  {
    name: 'Java',
    years: '1 year',
    category: 'Language',
    proficiency: onBusiness,
    picture: '/icons/Java.svg',
    pictureColor: '#61DAFB',
  },
  {
    name: 'C,C++,C#',
    years: '6 months',
    category: 'Language',
    proficiency: onBusiness,
    picture: '/icons/C-Cpp-CSharp.svg',
    pictureColor: '#00599C',
  },
  {
    name: 'Python',
    years: '1 year',
    category: 'Language',
    proficiency: onBusiness,
    picture: '/icons/Python.svg',
    pictureColor: '#3776AB',
  },
  {
    name: 'React',
    years: '1 year 6 months',
    category: 'Frontend',
    proficiency: onBusiness,
    picture: '/icons/React.svg',
    pictureColor: '#61DAFB',
  },
  {
    name: 'Next.js',
    years: '6 months',
    category: 'Frontend',
    proficiency: onBusiness,
    picture: '/icons/Next.js.svg',
    pictureColor: '#000000',
  },
  {
    name: 'Node.js',
    years: '1 year',
    category: 'Backend',
    proficiency: onBusiness,
    picture: '/icons/Node.js.svg',
    pictureColor: '#5FA04E',
  },
  {
    name: 'Express.js',
    years: selfStudy,
    category: 'Backend',
    proficiency: selfStudy,
    picture: '/icons/Express.js.svg',
    pictureColor: '#5FA04E',
  },
  {
    name: 'Hono.js',
    years: selfStudy,
    category: 'Backend',
    proficiency: selfStudy,
    picture: '/icons/Hono.js.svg',
    pictureColor: '#E36002',
  },
  {
    name: 'Springboot(Java)',
    years: '1 year',
    category: 'Backend',
    proficiency: onBusiness,
    picture: '/icons/SpringBoot.svg',
    pictureColor: '#6DB33F',
  },
  {
    name: 'GraphQL',
    years: '1 year 6 months',
    category: 'API',
    proficiency: onBusiness,
    picture: '/icons/GraphQL.svg',
    pictureColor: '#E10098',
  },
  {
    name: 'REST',
    years: '2 years',
    category: 'API',
    proficiency: onBusiness,
    picture: '/icons/REST.svg',
    pictureColor: '#61DAFB',
  },
  {
    name: 'Axios(REST)',
    years: '1 year',
    category: 'API',
    proficiency: onBusiness,
    picture: '/icons/Axios-REST.svg',
    pictureColor: '#311C87',
  },
  {
    name: 'Redux',
    years: selfStudy,
    category: 'State Management',
    proficiency: selfStudy,
    picture: '/icons/Redux.svg',
    pictureColor: '#764ABC',
  },
  {
    name: 'Context API',
    years: '6 months',
    category: 'State Management',
    proficiency: onBusiness,
    picture: '/icons/Redux.svg',
    pictureColor: '#764ABC',
  },
  {
    name: 'Prisma',
    years: selfStudy,
    category: 'ORM',
    proficiency: selfStudy,
    picture: '/icons/Prisma.svg',
    pictureColor: '#2D3748',
  },
  {
    name: 'Selenium(Python)',
    years: '1 year',
    category: 'Testing',
    proficiency: onBusiness,
    picture: '/icons/Selenium-Python.svg',
    pictureColor: '#43B02A',
  },
  {
    name: 'Jest',
    years: '6 months',
    category: 'Testing',
    proficiency: onBusiness,
    picture: '/icons/Jest.svg',
    pictureColor: '#C21325',
  },
  {
    name: 'Vitest',
    years: '3 months',
    category: 'Testing',
    proficiency: onBusiness,
    picture: '/icons/Vitest.svg',
    pictureColor: '#C21325',
  },
  {
    name: 'BootStrap5',
    years: '1 year',
    category: 'CSS',
    proficiency: onBusiness,
    picture: '/icons/BootStrap5.svg',
    pictureColor: '#7952B3',
  },
  {
    name: 'TailWindCSS',
    years: selfStudy,
    category: 'CSS',
    proficiency: selfStudy,
    picture: '/icons/TailWindCSS.svg',
    pictureColor: '#06B6D4',
  },
  {
    name: 'MySQL',
    years: '1 year',
    category: 'Database',
    proficiency: onBusiness,
    picture: '/icons/MySQL.svg',
    pictureColor: '#4479A1',
  },
  {
    name: 'PostgresSQL',
    years: '6 months',
    category: 'Database',
    proficiency: onBusiness,
    picture: '/icons/PostgresSQL.svg',
    pictureColor: '#336791',
  },
  {
    name: 'Redis',
    years: '6 months',
    category: 'Database',
    proficiency: onBusiness,
    picture: '/icons/Redis.svg',
    pictureColor: '#4479A1',
  },
  {
    name: 'Vercel',
    years: '6 months',
    category: 'Database',
    proficiency: onBusiness,
    picture: '/icons/Vercel.svg',
    pictureColor: '#000000',
  },
  {
    name: 'AWS',
    years: '3 months',
    category: 'Cloud',
    proficiency: onBusiness,
    picture: '/icons/AWS.svg',
    pictureColor: '#232F3E',
  },
  {
    name: 'Azure',
    years: '1 year',
    category: 'Cloud',
    proficiency: onBusiness,
    picture: '/icons/Azure.svg',
    pictureColor: '#0089D6',
  },
  {
    name: 'Docker',
    years: '6 months',
    category: 'Others',
    proficiency: onBusiness,
    picture: '/icons/Docker.svg',
    pictureColor: '#2496ED',
  },
  {
    name: 'shadcn',
    years: selfStudy,
    category: 'Frontend',
    proficiency: selfStudy,
    picture: '/icons/shadcn.svg',
    pictureColor: '#000000',
  },
  {
    name: 'Material UI',
    years: '6 months',
    category: 'Frontend',
    proficiency: onBusiness,
    picture: '/icons/Material-UI.svg',
    pictureColor: '#007FFF',
  },
  {
    name: 'React Hook Form',
    years: '1 year 6 months',
    category: 'Frontend',
    proficiency: onBusiness,
    picture: '/icons/ReactHookForm.svg',
    pictureColor: '#FF6B35',
  },
  {
    name: 'zod',
    years: '6 months',
    category: 'Frontend',
    proficiency: onBusiness,
    picture: '/icons/Zod.svg',
    pictureColor: '#3E67B1',
  },
  {
    name: 'NextAuth',
    years: '6 months',
    category: 'Frontend',
    proficiency: onBusiness,
    picture: '/icons/NextAuth.png',
    pictureColor: '#000000',
  },
  {
    name: 'codegen',
    years: '6 months',
    category: 'Frontend',
    proficiency: onBusiness,
    picture: '/icons/Codegen.svg',
    pictureColor: '#E10098',
  },
  {
    name: 'Dwolla',
    years: selfStudy,
    category: 'Others',
    proficiency: selfStudy,
    picture: '/icons/Dwolla.svg',
    pictureColor: '#FF6A13',
  },
  {
    name: 'babylon.js',
    years: selfStudy,
    category: 'Frontend',
    proficiency: selfStudy,
    picture: '/icons/BabylonJS.svg',
    pictureColor: '#BB464B',
  },
  {
    name: 'kaPlay',
    years: selfStudy,
    category: 'Frontend',
    proficiency: selfStudy,
    picture: '/icons/KaPlay.svg',
    pictureColor: '#4CAF50',
  },
  {
    name: 'AstraDB',
    years: selfStudy,
    category: 'Database',
    proficiency: selfStudy,
    picture: '/icons/AstraDB.svg',
    pictureColor: '#FF6B6B',
  },
];

// otherSkills(IDE,Editor,Project Management Tool.etc)
export const otherSkills: SkillItem[] = [
  {
    name: 'VS Code(Typescript)',
    years: '1 year',
    category: 'Others',
    proficiency: onBusiness,
    picture: '/icons/VSCode.svg',
    pictureColor: '#007ACC',
  },
  {
    name: 'Windsurf',
    years: '6 months',
    category: 'Others',
    proficiency: onBusiness,
    picture: '/icons/Windsurf.svg',
    pictureColor: '#007ACC',
  },
  {
    name: 'IntelliJ IDEA(Typescript)',
    years: '1 year',
    category: 'Others',
    proficiency: onBusiness,
    picture: '/icons/IntelliJIDEA.svg',
    pictureColor: '#000000',
  },
  {
    name: 'Eclipse(Java,Javascript)',
    years: '6 months',
    category: 'Others',
    proficiency: onBusiness,
    picture: '/icons/Eclipse.svg',
    pictureColor: '#0089D6',
  },
  {
    name: 'Spring Tool Suite4(Java,Javascript)',
    years: '4 months',
    category: 'Others',
    proficiency: onBusiness,
    picture: '/icons/SpringToolSuite.svg',
    pictureColor: '#6DB33F',
  },
  {
    name: 'StackBlitz(React)',
    years: selfStudy,
    category: 'Others',
    proficiency: selfStudy,
    picture: '/icons/StackBlitz.svg',
    pictureColor: '#1269D3',
  },
  {
    name: 'Visual Studio(C,C++,C#)',
    years: '8 months',
    category: 'Others',
    proficiency: onBusiness,
    picture: '/icons/Visual-Studio-C-Cpp-CSharp.svg',
    pictureColor: '#5C2D91',
  },
  {
    name: 'Git(Tortoise Git)',
    years: '1 year',
    category: 'Others',
    proficiency: onBusiness,
    picture: '/icons/Git-Tortoise-Git.svg',
    pictureColor: '#F05032',
  },
  {
    name: 'Github',
    years: '1 year',
    category: 'Others',
    proficiency: onBusiness,
    picture: '/icons/Github.svg',
    pictureColor: '#181717',
  },
  {
    name: 'Swagger',
    years: '6 months',
    category: 'Others',
    proficiency: onBusiness,
    picture: '/icons/Swagger.svg',
    pictureColor: '#85EA2D',
  },
  {
    name: 'Backlog',
    years: '1 year',
    category: 'Others',
    proficiency: onBusiness,
    picture: '/icons/Backlog.svg',
    pictureColor: '#181717',
  },
  {
    name: 'Redmine',
    years: '3 months',
    category: 'Others',
    proficiency: onBusiness,
    picture: '/icons/Redmine.svg',
    pictureColor: '#B32024',
  },
  {
    name: 'Asana',
    years: '1 month',
    category: 'Others',
    proficiency: onBusiness,
    picture: '/icons/Asana.svg',
    pictureColor: '#F06A6A',
  },
  {
    name: 'A5:SQL Mk-2',
    years: '1 year',
    category: 'Others',
    proficiency: onBusiness,
    picture: '/icons/A5SQLMk2.svg',
    pictureColor: '#336791',
  },
  {
    name: 'Bun',
    years: selfStudy,
    category: 'Others',
    proficiency: selfStudy,
    picture: '/icons/Bun.svg',
    pictureColor: '#000000',
  },
];
