import {onBusiness, selfStudy} from './common';
import type {SkillItem} from '../types/skillItem';

// main skills(Language,Libraries)
export const skills: SkillItem[] = [
  {
    name: 'TypeScript',
    years: '1 year 6 months',
    category: 'Language',
    proficiency: onBusiness,
    picture: '/icons/TypeScript.svg',
    pictureColor: '#3178C6',
  },
  {
    name: 'JavaScript(include TypeScript)',
    years: '2 years',
    category: 'Language',
    proficiency: onBusiness,
    picture: '/icons/JavaScript.svg',
    pictureColor: '#F7DF1E',
  },
  {
    name: 'Java',
    years: '2 years',
    category: 'Language',
    proficiency: onBusiness,
    picture: '/icons/Java.svg',
    pictureColor: '#61DAFB',
  },
  {
    name: 'C,C++,C#',
    years: '6 months',
    category: 'Language',
    proficiency: onBusiness,
    picture: '/icons/C-Cpp-CSharp.svg',
    pictureColor: '#00599C',
  },
  {
    name: 'Python',
    years: '2 years',
    category: 'Language',
    proficiency: onBusiness,
    picture: '/icons/Python.svg',
    pictureColor: '#3776AB',
  },
  {
    name: 'React',
    years: '2 years',
    category: 'Frontend',
    proficiency: onBusiness,
    picture: '/icons/React.svg',
    pictureColor: '#61DAFB',
  },
  {
    name: 'Next.js',
    years: '1 year',
    category: 'Frontend',
    proficiency: onBusiness,
    picture: '/icons/Next.js.svg',
    pictureColor: '#000000',
  },
  {
    name: 'Node.js',
    years: '2 years',
    category: 'Backend',
    proficiency: onBusiness,
    picture: '/icons/Node.js.svg',
    pictureColor: '#5FA04E',
  },
  {
    name: 'Express.js',
    years: selfStudy,
    category: 'Backend',
    proficiency: selfStudy,
    picture: '/icons/Express.js.svg',
    pictureColor: '#5FA04E',
  },
  {
    name: 'Hono.js',
    years: '6 months',
    category: 'Backend',
    proficiency: onBusiness,
    picture: '/icons/Hono.js.svg',
    pictureColor: '#E36002',
  },
  {
    name: 'Springboot(Java)',
    years: '2 years',
    category: 'Backend',
    proficiency: onBusiness,
    picture: '/icons/SpringBoot.svg',
    pictureColor: '#6DB33F',
  },
  {
    name: 'GraphQL',
    years: '2 years',
    category: 'API',
    proficiency: onBusiness,
    picture: '/icons/GraphQL.svg',
    pictureColor: '#E10098',
  },
  {
    name: 'REST',
    years: '2 years',
    category: 'API',
    proficiency: onBusiness,
    picture: '/icons/REST.svg',
    pictureColor: '#61DAFB',
  },
  {
    name: 'Redux',
    years: selfStudy,
    category: 'State Management',
    proficiency: selfStudy,
    picture: '/icons/Redux.svg',
    pictureColor: '#764ABC',
  },
  {
    name: 'Context API',
    years: '1 year',
    category: 'State Management',
    proficiency: onBusiness,
    picture: '/icons/Redux.svg',
    pictureColor: '#764ABC',
  },
  {
    name: 'Prisma',
    years: selfStudy,
    category: 'ORM',
    proficiency: selfStudy,
    picture: '/icons/Prisma.svg',
    pictureColor: '#2D3748',
  },
  {
    name: 'Selenium(Python)',
    years: '1 year',
    category: 'Testing',
    proficiency: onBusiness,
    picture: '/icons/Selenium-Python.svg',
    pictureColor: '#43B02A',
  },
  {
    name: 'Playwright(TypeScript)',
    years: '1 year',
    category: 'Testing',
    proficiency: onBusiness,
    picture: '/icons/Playwright.svg',
    pictureColor: '#C21325',
  },
  {
    name: 'Jest',
    years: '6 months',
    category: 'Testing',
    proficiency: onBusiness,
    picture: '/icons/Jest.svg',
    pictureColor: '#C21325',
  },
  {
    name: 'Vitest',
    years: '6 months',
    category: 'Testing',
    proficiency: onBusiness,
    picture: '/icons/Vitest.svg',
    pictureColor: '#C21325',
  },
  {
    name: 'BootStrap5',
    years: '1 year',
    category: 'CSS',
    proficiency: onBusiness,
    picture: '/icons/BootStrap5.svg',
    pictureColor: '#7952B3',
  },
  {
    name: 'Tailwind CSS',
    years: '1 year',
    category: 'CSS',
    proficiency: onBusiness,
    picture: '/icons/TailWindCSS.svg',
    pictureColor: '#06B6D4',
  },
  {
    name: 'MySQL',
    years: '1 year',
    category: 'Database',
    proficiency: onBusiness,
    picture: '/icons/MySQL.svg',
    pictureColor: '#4479A1',
  },
  {
    name: 'PostgreSQL',
    years: '1 year',
    category: 'Database',
    proficiency: onBusiness,
    picture: '/icons/PostgresSQL.svg',
    pictureColor: '#336791',
  },
  {
    name: 'Redis',
    years: '1 year',
    category: 'Database',
    proficiency: onBusiness,
    picture: '/icons/Redis.svg',
    pictureColor: '#4479A1',
  },
  {
    name: 'Vercel',
    years: '1 year',
    category: 'Database',
    proficiency: onBusiness,
    picture: '/icons/Vercel.svg',
    pictureColor: '#000000',
  },
  {
    name: 'AWS',
    years: '3 months',
    category: 'Cloud',
    proficiency: onBusiness,
    picture: '/icons/AWS.svg',
    pictureColor: '#232F3E',
  },
  {
    name: 'Azure',
    years: '2 years',
    category: 'Cloud',
    proficiency: onBusiness,
    picture: '/icons/Azure.svg',
    pictureColor: '#0089D6',
  },
  {
    name: 'Docker',
    years: '1 year',
    category: 'Others',
    proficiency: onBusiness,
    picture: '/icons/Docker.svg',
    pictureColor: '#2496ED',
  },
  {
    name: 'shadcn',
    years: '1 year',
    category: 'Frontend',
    proficiency: onBusiness,
    picture: '/icons/shadcn.svg',
    pictureColor: '#000000',
  },
  {
    name: 'Material UI',
    years: '1 year',
    category: 'Frontend',
    proficiency: onBusiness,
    picture: '/icons/Material-UI.svg',
    pictureColor: '#007FFF',
  },
  {
    name: 'React Hook Form',
    years: '2 years',
    category: 'Frontend',
    proficiency: onBusiness,
    picture: '/icons/ReactHookForm.svg',
    pictureColor: '#FF6B35',
  },
  {
    name: 'zod',
    years: '1 year',
    category: 'Frontend',
    proficiency: onBusiness,
    picture: '/icons/Zod.svg',
    pictureColor: '#3E67B1',
  },
  {
    name: 'NextAuth',
    years: '1 year',
    category: 'Frontend',
    proficiency: onBusiness,
    picture: '/icons/NextAuth.png',
    pictureColor: '#000000',
  },
  {
    name: 'codegen',
    years: '1 year',
    category: 'Frontend',
    proficiency: onBusiness,
    picture: '/icons/Codegen.svg',
    pictureColor: '#E10098',
  },
  {
    name: 'babylon.js',
    years: selfStudy,
    category: 'Frontend',
    proficiency: selfStudy,
    picture: '/icons/BabylonJS.svg',
    pictureColor: '#BB464B',
  },
  {
    name: 'kaPlay',
    years: selfStudy,
    category: 'Frontend',
    proficiency: selfStudy,
    picture: '/icons/KaPlay.svg',
    pictureColor: '#4CAF50',
  },
  {
    name: 'vectorDB(pgvector)',
    years: "3 months",
    category: 'Database',
    proficiency: onBusiness,
    picture: '/icons/AstraDB.svg',
    pictureColor: '#FF6B6B',
  },
];

// otherSkills(IDE,Editor,Project Management Tool.etc)
export const otherSkills: SkillItem[] = [
  {
    name: 'VS Code(Typescript)',
    years: '2 year',
    category: 'Others',
    proficiency: onBusiness,
    picture: '/icons/VSCode.svg',
    pictureColor: '#007ACC',
  },
{
    name: 'IntelliJ IDEA(Typescript)',
    years: '1 year',
    category: 'Others',
    proficiency: onBusiness,
    picture: '/icons/IntelliJIDEA.svg',
    pictureColor: '#000000',
  },
  {
    name: 'Eclipse(Java,Javascript)',
    years: '1 year',
    category: 'Others',
    proficiency: onBusiness,
    picture: '/icons/Eclipse.svg',
    pictureColor: '#0089D6',
  },
  {
    name: 'Spring Tool Suite4(Java,Javascript)',
    years: '4 months',
    category: 'Others',
    proficiency: onBusiness,
    picture: '/icons/SpringToolSuite.svg',
    pictureColor: '#6DB33F',
  },
  {
    name: 'StackBlitz(React)',
    years: selfStudy,
    category: 'Others',
    proficiency: selfStudy,
    picture: '/icons/StackBlitz.svg',
    pictureColor: '#1269D3',
  },
  {
    name: 'Visual Studio(C,C++,C#)',
    years: '8 months',
    category: 'Others',
    proficiency: onBusiness,
    picture: '/icons/Visual-Studio-C-Cpp-CSharp.svg',
    pictureColor: '#5C2D91',
  },
  {
    name: 'Git(Tortoise Git)',
    years: '2 year',
    category: 'Others',
    proficiency: onBusiness,
    picture: '/icons/Git-Tortoise-Git.svg',
    pictureColor: '#F05032',
  },
  {
    name: 'Github',
    years: '2 year',
    category: 'Others',
    proficiency: onBusiness,
    picture: '/icons/Github.svg',
    pictureColor: '#181717',
  },
  {
    name: 'Swagger',
    years: '6 months',
    category: 'Others',
    proficiency: onBusiness,
    picture: '/icons/Swagger.svg',
    pictureColor: '#85EA2D',
  },
  {
    name: 'Backlog',
    years: '1 year',
    category: 'Others',
    proficiency: onBusiness,
    picture: '/icons/Backlog.svg',
    pictureColor: '#181717',
  },
{
    name: 'A5:SQL Mk-2',
    years: '1 year',
    category: 'Others',
    proficiency: onBusiness,
    picture: '/icons/A5SQLMk2.svg',
    pictureColor: '#336791',
  },
  {
    name: 'Bun',
    years: selfStudy,
    category: 'Others',
    proficiency: selfStudy,
    picture: '/icons/Bun.svg',
    pictureColor: '#000000',
  },
];

// type-safe skill name accessor
// S.typescript => 'TypeScript', S.nextJs => 'Next.js', etc.
const allSkills = [...skills, ...otherSkills];
const n = <T extends typeof allSkills[number]['name']>(name: T): T => {
  if (!allSkills.some(skill => skill.name === name)) {
    throw new Error(`Skill not found: ${name}`);
  }
  return name;
};

export const S = {
  typescript: n('TypeScript'),
  javascript: n('JavaScript(include TypeScript)'),
  java: n('Java'),
  cFamily: n('C,C++,C#'),
  python: n('Python'),
  react: n('React'),
  nextJs: n('Next.js'),
  nodeJs: n('Node.js'),
  expressJs: n('Express.js'),
  honoJs: n('Hono.js'),
  springboot: n('Springboot(Java)'),
  graphql: n('GraphQL'),
  rest: n('REST'),
  redux: n('Redux'),
  contextApi: n('Context API'),
  prisma: n('Prisma'),
  selenium: n('Selenium(Python)'),
  playwright: n('Playwright(TypeScript)'),
  jest: n('Jest'),
  vitest: n('Vitest'),
  bootstrap5: n('BootStrap5'),
  tailwind: n('Tailwind CSS'),
  mysql: n('MySQL'),
  postgresql: n('PostgreSQL'),
  redis: n('Redis'),
  vercel: n('Vercel'),
  aws: n('AWS'),
  azure: n('Azure'),
  docker: n('Docker'),
  shadcn: n('shadcn'),
  materialUi: n('Material UI'),
  reactHookForm: n('React Hook Form'),
  zod: n('zod'),
  nextAuth: n('NextAuth'),
  codegen: n('codegen'),
  babylonJs: n('babylon.js'),
  kaPlay: n('kaPlay'),
  vectorDb: n('vectorDB(pgvector)'),
  vsCode: n('VS Code(Typescript)'),
  intellij: n('IntelliJ IDEA(Typescript)'),
  eclipse: n('Eclipse(Java,Javascript)'),
  sts4: n('Spring Tool Suite4(Java,Javascript)'),
  stackBlitz: n('StackBlitz(React)'),
  visualStudio: n('Visual Studio(C,C++,C#)'),
  git: n('Git(Tortoise Git)'),
  github: n('Github'),
  swagger: n('Swagger'),
  backlog: n('Backlog'),
  a5sql: n('A5:SQL Mk-2'),
  bun: n('Bun'),
} as const;

// skill sets
export const nextjsSkillSet = [
  S.react,
  S.typescript,
  S.nextJs,
  S.tailwind,
  S.shadcn,
  S.vercel,
];

export const receptionInnovationSkillSet = [
  S.typescript,
  S.react,
  S.nodeJs,
  S.mysql,
  S.selenium,
  'little state machine',
  S.reactHookForm,
  'axios',
  'TypeORM',
  'class-validator',
  'Apollo Client Server(GraphQL)',
  S.bootstrap5,
  'Azure(App Service,Azure Functions)',
  S.backlog,
  S.swagger,
  'アジャイル開発(スクラム)',
];

export const VOCSkillSet = [
  S.typescript,
  S.react,
  S.java,
  S.springboot,
  S.mysql,
  S.selenium,
  'Mybatis(Java ORM)',
  'axios',
  S.backlog,
  'アジャイル開発(スクラム)',
];

export const T3StackSkillSet = [
  S.react,
  S.typescript,
  S.nextJs,
  'Prisma(or Drizzle)',
  'tRPC',
  S.tailwind,
];
